### ISSUE TITLE
EPUB i foreløpig publisering

### ISSUE THREAD

**Issue by jimjyang** [difi/forvaltningsstandard-begrepskoordinering#10]
- [ ] Tittelsiden(e) er tomme (de to første sidene som tilsvarende de to første i PDF er tomme, "UNTITLED", i hvert fall i min app ePub på iPhone). 
- [ ] Dokument-interne lenker virker ikke.

**Comment by stigbd** [comment]
Epub er tatt bort i ac212c2886e994888c588af404942301197c9441
Ref #13
